import pytest
import re
from playwright.sync_api import sync_playwright, Page, expect
import time


@pytest.fixture(scope="class")
def browser_context():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)  # 可视化模式
        context = browser.new_context(
            viewport={"width": 1920, "height": 1080}
        )
        yield context
        # context.close()
        # browser.close()


@pytest.fixture(scope="class")
def logged_in_page(browser_context) -> Page:
    page = browser_context.new_page()
    page.goto(
        "http://192.168.111.232:18901/login?haveWarehouse=1&client_id=iowtb-new&redirect_uri=http://192.168.111.232:9832/login")
    page.get_by_placeholder("请输入账号").click()
    page.get_by_placeholder("请输入账号").fill("ssoadmintest6")
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").fill("lhx7758521")
    page.locator("#warehouse").select_option("1")
    page.get_by_role("button", name="登录").click()
    expect(page.locator("header")).to_contain_text("首页")
    yield page
    # page.close()


class TestBasicPage:

    def test_login(self, logged_in_page: Page) -> None:
        # 这里的测试用例可以验证登录后的状态
        expect(logged_in_page.locator("header")).to_contain_text("首页")

    def test_basic_warehouse(self, logged_in_page: Page) -> None:
        # 直接使用已登录的页面
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓库档案$")).click()
        logged_in_page.get_by_text("仓库档案").nth(1).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("CSCK1")
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_label("remove").nth(1).click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_basic_warehouse_location(self, logged_in_page: Page) -> None:
        # 直接使用已登录的页面
        logged_in_page.locator("li").filter(has_text="库内移动规则").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("规则编号").click()
        logged_in_page.get_by_label("规则编号").fill("auto")
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("移库").locator("div").click()
        logged_in_page.locator(
            "div:nth-child(3) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_title("人工作业").locator("div").click()
        logged_in_page.locator(
            "div:nth-child(4) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_title("D", exact=True).locator("div").click()
        logged_in_page.locator(
            "div:nth-child(5) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_text("虚拟拆零复核库区").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^请输入$")).nth(4).click()
        logged_in_page.get_by_text("整件库区").nth(3).click()
        logged_in_page.get_by_role("button", name="确 定").nth(1).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("auto")
        logged_in_page.locator(
            'xpath=//*[@id="app"]/section/section/section/div[3]/div/div/div[3]/div[2]/div/div/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div/div/div/div[2]/input').check()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("LD0001")

    def test_owner_page(self, logged_in_page: Page) -> None:
        # 直接使用已登录的页面
        logged_in_page.locator("div").filter(has_text=re.compile(r"^业主货主档案$")).click()
        logged_in_page.locator("li").filter(has_text=re.compile(r"^业主货主档案 货主列表$")).get_by_role(
            "listitem").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_label("remove").nth(3).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        time.sleep(0.5)
        logged_in_page.get_by_role("button", name="确 定").nth(1).click()

    def test_location_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("div").filter(has_text=re.compile(r"^货位档案$")).click()
        logged_in_page.locator("#app").get_by_text("库房货位资料维护").click()
        logged_in_page.get_by_role("tree").get_by_text("默认仓库").click()
        logged_in_page.get_by_role("button", name="保 存").click()
        logged_in_page.get_by_role("button", name="新增").click()
        time.sleep(0.5)
        logged_in_page.locator("td:nth-child(3) > .vxe-cell").first.click()
        logged_in_page.get_by_role("cell", name="库别编码未填写").get_by_role("textbox").fill("QD")
        logged_in_page.locator("td:nth-child(4) > .vxe-cell").first.dblclick()
        logged_in_page.get_by_role("cell", name="库别名称未填写").get_by_role("textbox").fill("auto")
        logged_in_page.locator("td:nth-child(7) > .vxe-cell").first.click()
        logged_in_page.get_by_role("row", name="QD auto 默认仓库   启用").get_by_role("textbox").fill("1000")
        time.sleep(0.5)
        logged_in_page.get_by_role("row", name=" 1").get_by_role("cell").first.click()
        logged_in_page.get_by_role("button", name="保 存").click()
        time.sleep(0.5)
        logged_in_page.get_by_role("cell", name="auto").locator("div").click()
        logged_in_page.locator("#app").get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_zcq_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="暂存区维护").nth(2).click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        # logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.locator(
            'xpath=//*[@id="app"]/section/section/section/div[3]/div/div/div[3]/div[1]/div[1]/button[1]/span').click()
        logged_in_page.get_by_label("暂存区类型").click()
        logged_in_page.get_by_label("新增").get_by_text("虚拟暂存区").click()
        logged_in_page.get_by_label("暂存区编号").click()
        logged_in_page.get_by_label("暂存区编号").fill("ZT-666")
        logged_in_page.locator(
            "div:nth-child(5) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector").nth(
            1).click()
        logged_in_page.get_by_label("新增").get_by_text("ToB").click()
        logged_in_page.get_by_text("启用", exact=True).nth(1).click()
        logged_in_page.get_by_text("停用").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        # logged_in_page.locator(".ant-form-item-control-input").nth(2).click()
        # logged_in_page.locator(
        #     'xpath=//*[@id="app"]/section/section/section/div[3]/div/div/div[3]/div[2]/div/div/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div/div/div/div[2]/imput').first.click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="删 除").first.click()
        logged_in_page.get_by_role("button", name="确 定").nth(2).click()

    def test_user_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("div").filter(has_text=re.compile(r"^业务组织$")).click()
        logged_in_page.locator("li").filter(has_text="用户基础资料").nth(1).click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^业务组织$")).click()
        logged_in_page.get_by_text("用户基础资料").first.click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()

    def test_department_page(self, logged_in_page: Page) -> None:
        logged_in_page.get_by_text("部门资料").first.click()
        logged_in_page.get_by_label("部门编码").click()
        logged_in_page.get_by_label("部门编码").fill("test123")
        logged_in_page.get_by_label("部门名称").click()
        logged_in_page.get_by_label("部门名称").fill("testtest")
        logged_in_page.locator("#app div").filter(has_text=re.compile(r"^请选择$")).nth(4).click()
        time.sleep(0.5)
        logged_in_page.get_by_text("否", exact=True).nth(0).click()
        logged_in_page.get_by_role("button", name="保 存").click()
        logged_in_page.get_by_title("testtest").click()
        time.sleep(0.5)
        logged_in_page.get_by_role("button", name="删 除").first.click()
        logged_in_page.get_by_role("button", name="确 定").nth(2).click()

    def test_user_group_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="人员安排表").nth(1).click()
        logged_in_page.get_by_text("收货").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="取 消").nth(2).click()
        logged_in_page.locator(".action_btn > div:nth-child(3) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="取 消").nth(2).click()
        logged_in_page.locator(".action_btn > div:nth-child(4) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="取 消").nth(2).click()

    def test_department_relation_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="业务部门关系表").nth(1).click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.locator(".action_btn > div:nth-child(3) > .ant-btn").first.click()
        logged_in_page.locator(".action_btn > div:nth-child(3) > .ant-btn").first.click()
        logged_in_page.locator(".action_btn > div:nth-child(4) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="取 消").nth(2).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("测试科技有限公司")
        logged_in_page.get_by_role("button", name="新 增").first.click()
        logged_in_page.get_by_role("button", name="取 消").nth(2).click()

    def test_basic_customer_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.locator("li").filter(has_text="客户资料维护").nth(1).click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.locator("li").filter(has_text="客户资料维护").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").first.click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("客户编号").click()
        logged_in_page.get_by_label("客户编号").fill("uitest")
        logged_in_page.locator("form").filter(
            has_text="客户编号助记码业主编码客户简称客户名称来源系统:请选择状态请选择客户分类请选择").locator(
            "#form_item_mnemonicCode").click()
        logged_in_page.locator("form").filter(
            has_text="客户编号助记码业主编码客户简称客户名称来源系统:请选择状态请选择客户分类请选择").locator(
            "#form_item_mnemonicCode").fill("ui")
        logged_in_page.get_by_label("客户简称").click()
        logged_in_page.get_by_label("客户简称").fill("customerui1")
        logged_in_page.get_by_label("客户名称").click()
        logged_in_page.get_by_label("客户名称").fill("customerui1")
        logged_in_page.get_by_label("来源系统:").click()
        logged_in_page.get_by_title("WMS", exact=True).locator("div").click()
        logged_in_page.locator("form").filter(has_text="客户编号助记码业主编码客户简称客户名称来源系统:").locator(
            "#form_item_isEnable").click()
        logged_in_page.get_by_title("停用").locator("div").click()
        logged_in_page.get_by_label("客户分类").click()
        logged_in_page.get_by_title("药品批发企业").locator("div").click()
        logged_in_page.get_by_role("button", name="添加地址信息").click()
        logged_in_page.locator(".vxe-cell > div > .ant-select > .ant-select-selector").first.click()
        logged_in_page.get_by_title("北京").click()
        logged_in_page.locator("td:nth-child(4) > .vxe-cell > div > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_title("北京市").click()
        logged_in_page.locator("td:nth-child(5) > .vxe-cell > div > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_title("东城区").nth(1).click()
        logged_in_page.locator("td:nth-child(7) > .vxe-cell > div > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_text("不分方向").click()
        logged_in_page.get_by_role("cell", name="请输入").locator("div").nth(3).click()
        logged_in_page.get_by_text("不分线路").click()
        logged_in_page.locator("td:nth-child(10) > .vxe-cell").click()
        logged_in_page.get_by_role("row", name=" 1").get_by_role("textbox").fill("12345")
        logged_in_page.locator("td:nth-child(11)").click()
        logged_in_page.get_by_role("cell", name="请输入纬度").get_by_role("textbox").fill("123")
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("uitest")
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_basic_supplier_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.get_by_text("供应商资料维护").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.get_by_text("供应商资料维护", exact=True).first.click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("供应商编号").click()
        logged_in_page.get_by_label("供应商编号").fill("autoui")
        logged_in_page.locator("form").filter(
            has_text="供应商编号助记码集团编码供应商简称供应商名称来源系统请选择外部编码是否活动请选择供应商类型请选择").locator(
            "#form_item_mnemonicCode").click()
        logged_in_page.locator("form").filter(
            has_text="供应商编号助记码集团编码供应商简称供应商名称来源系统请选择外部编码是否活动请选择供应商类型请选择").locator(
            "#form_item_mnemonicCode").fill("autoui")
        logged_in_page.get_by_label("供应商简称").click()
        logged_in_page.get_by_label("供应商简称").fill("uitest")
        logged_in_page.get_by_label("供应商名称").click()
        logged_in_page.get_by_label("供应商名称").fill("uitest")
        logged_in_page.get_by_label("来源系统").click()
        logged_in_page.get_by_title("WMS", exact=True).locator("div").click()
        logged_in_page.get_by_label("外部编码").click()
        logged_in_page.get_by_label("外部编码").fill("ui")
        logged_in_page.locator("form").filter(has_text="供应商编号助记码集团编码供应商简称供应商名称来源系统").locator(
            "#form_item_isEnable").click()
        logged_in_page.get_by_title("停用").click()
        logged_in_page.get_by_label("供应商类型").click()
        logged_in_page.get_by_title("商业客户").locator("div").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("button", name="确 定").nth(1).click()

    def test_basic_shop_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.locator("li").filter(has_text="店铺档案").nth(1).click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.locator("li").filter(has_text="店铺档案").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(4) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(3) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("店铺编号").click()
        logged_in_page.get_by_label("店铺编号").fill("testui")
        logged_in_page.get_by_label("店铺简称").click()
        logged_in_page.get_by_label("店铺简称").fill("testui")
        logged_in_page.get_by_label("全称").click()
        logged_in_page.get_by_label("全称").fill("testui")
        logged_in_page.get_by_label("类型", exact=True).click()
        logged_in_page.get_by_title("门店").locator("div").click()
        logged_in_page.get_by_label("来源系统").click()
        logged_in_page.get_by_title("WMS", exact=True).locator("div").click()
        logged_in_page.get_by_label("来源公司编码").click()
        logged_in_page.get_by_label("来源公司编码").fill("uitest")
        logged_in_page.get_by_label("外部编码").click()
        logged_in_page.get_by_label("外部编码").fill("123")
        logged_in_page.locator("form").filter(has_text="店铺编号店铺简称全称类型门店MDWD门店网店来源系统").locator(
            "#form_item_mnemonicCode").click()
        logged_in_page.locator("form").filter(has_text="店铺编号店铺简称全称类型门店MDWD门店网店来源系统").locator(
            "#form_item_mnemonicCode").fill("123")
        logged_in_page.get_by_label("联系人").click()
        logged_in_page.get_by_label("联系人").fill("测试人员")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282391")
        logged_in_page.locator(
            ".zhqc-collapse-container__body > .ant-form > div > div:nth-child(11) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-affix-wrapper").click()
        logged_in_page.get_by_label("联系地址").fill("青岛市市北区")
        logged_in_page.get_by_label("联系手机").click()
        logged_in_page.get_by_label("联系手机").fill("18660282391")
        logged_in_page.get_by_label("联系邮箱").click()
        logged_in_page.get_by_label("联系邮箱").fill("test123")
        logged_in_page.get_by_label("所属平台").click()
        logged_in_page.get_by_text("淘宝").click()
        logged_in_page.get_by_label("省份").click()
        logged_in_page.get_by_text("北京").click()
        logged_in_page.get_by_label("城市").click()
        logged_in_page.get_by_text("北京市").click()
        logged_in_page.get_by_label("区县").click()
        logged_in_page.get_by_text("东城区").nth(1).click()
        logged_in_page.locator("form").filter(has_text="店铺编号店铺简称全称类型门店MDWD门店网店来源系统").locator(
            "#form_item_isEnable").click()
        logged_in_page.get_by_title("停用").locator("div").click()
        logged_in_page.get_by_label("店铺平台编码").click()
        logged_in_page.get_by_label("店铺平台编码").fill("123")
        logged_in_page.get_by_label("电子面单平台").click()
        logged_in_page.get_by_text("淘宝电子面单平台").click()
        logged_in_page.locator("form").filter(has_text="店铺编号店铺简称全称类型门店MDWD门店网店来源系统").locator(
            "#form_item_remark").click()
        logged_in_page.locator("form").filter(has_text="店铺编号店铺简称全称类型门店MDWD门店网店来源系统").locator(
            "#form_item_remark").fill("ui测试用")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_label("联系邮箱").click()
        logged_in_page.get_by_label("联系邮箱").fill("1@qq.com")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_label("联系邮箱").click()
        logged_in_page.get_by_label("联系邮箱").dblclick()
        logged_in_page.get_by_label("联系邮箱").dblclick()
        logged_in_page.get_by_label("联系邮箱").click()
        logged_in_page.get_by_label("联系邮箱").fill("123@qq.com")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_basic_product_company_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.locator("span").filter(has_text="生产企业资料维护").first.click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^客商档案$")).click()
        logged_in_page.get_by_text("生产企业资料维护").first.click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(4) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(3) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("生产企业编码").click()
        logged_in_page.get_by_label("生产企业编码").fill("testui")
        logged_in_page.locator("form").filter(
            has_text="生产企业编码助记码生产企业简称生产企业名称来源系统请选择联系人联系电话联系地址传真手机邮箱是否启用启用建档人建档时间最终修改时间最终修改人").locator(
            "#form_item_mnemonicCode").click()
        logged_in_page.locator("form").filter(
            has_text="生产企业编码助记码生产企业简称生产企业名称来源系统请选择联系人联系电话联系地址传真手机邮箱是否启用启用建档人建档时间最终修改时间最终修改人").locator(
            "#form_item_mnemonicCode").fill("testui")
        logged_in_page.get_by_label("生产企业简称").click()
        logged_in_page.get_by_label("生产企业简称").fill("testui")
        logged_in_page.get_by_label("生产企业名称").click()
        logged_in_page.get_by_label("生产企业名称").fill("testui")
        logged_in_page.get_by_label("来源系统").click()
        logged_in_page.get_by_title("WMS", exact=True).locator("div").click()
        logged_in_page.get_by_label("联系人").click()
        logged_in_page.get_by_label("联系人").fill("测试人员")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282391")
        logged_in_page.get_by_label("联系地址").click()
        logged_in_page.get_by_label("联系地址").fill("测试地址")
        logged_in_page.get_by_label("手机").click()
        logged_in_page.get_by_label("手机").fill("18660282391")
        logged_in_page.get_by_label("邮箱").click()
        logged_in_page.get_by_label("邮箱").fill("1111111@qq.com")
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("testui")
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(4) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_basic_scope_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^商品档案$")).click()
        logged_in_page.locator("li").filter(has_text="经营范围类别").nth(1).click()
        logged_in_page.get_by_text("药品").click()
        expect(logged_in_page.locator("#app")).to_contain_text("苍穹ERP")
        logged_in_page.get_by_role("button", name="新增平级").click()
        logged_in_page.get_by_role("button", name="新增平级").click()
        logged_in_page.get_by_label("分类编码").click()
        logged_in_page.get_by_label("分类编码").fill("uitest")
        logged_in_page.get_by_label("分类名称", exact=True).click()
        logged_in_page.get_by_label("分类名称", exact=True).fill("ui测试用")
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("测试用")
        logged_in_page.get_by_role("button", name="保 存").click()
        expect(logged_in_page.get_by_role("tree")).to_contain_text("ui测试用")
        logged_in_page.get_by_title("ui测试用").locator("span").click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^药品$")).locator("svg").click()
        expect(logged_in_page.get_by_role("tree")).to_contain_text("处方药")

    def test_basic_business_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^商品档案$")).click()
        logged_in_page.locator("li").filter(has_text="商品基础资料").nth(1).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("智汇奇策科技有限公司")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_label("商品明细").get_by_text("智汇奇策科技有限公司").click()
        logged_in_page.get_by_role("tab", name="商品图片信息").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^GSP信息$")).first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^耗材$")).first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^产品包装数$")).first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^商品档案$")).click()
        logged_in_page.locator("li").filter(has_text="商品基础资料").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(3) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div:nth-child(4) > .ant-btn").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("产品编码").click()
        logged_in_page.get_by_label("产品编码").fill("uitest")
        logged_in_page.get_by_label("通用名称").click()
        logged_in_page.get_by_label("通用名称").fill("ui测试用")
        logged_in_page.get_by_label("商品名").click()
        logged_in_page.get_by_label("商品名").fill("UI测试用")
        logged_in_page.locator(
            ".zhqc-collapse-container__body > .ant-form > div > div:nth-child(4) > .ant-row > div:nth-child(2)").first.click()
        logged_in_page.locator('xpath=//*[@id="form_item_mnemonicCode"]').fill("uitest")
        logged_in_page.locator("div").filter(has_text=re.compile(r"^请输入$")).nth(3).click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").locator("div").click()
        logged_in_page.get_by_label("产品条码").click()
        logged_in_page.get_by_label("产品条码").fill("11111111")
        logged_in_page.get_by_role("combobox", name="经营范围类别").click()
        logged_in_page.get_by_label("商品明细").get_by_title("药品", exact=True).click()
        logged_in_page.get_by_label("产品类型").click()
        logged_in_page.get_by_title("药品", exact=True).nth(3).click()
        logged_in_page.get_by_label("规格").click()
        logged_in_page.get_by_label("规格").fill("50g")
        logged_in_page.get_by_label("单位").click()
        logged_in_page.get_by_label("单位").fill("青岛测试单位")
        logged_in_page.get_by_label("产地").click()
        logged_in_page.get_by_label("产地").fill("青岛市市北区")
        logged_in_page.get_by_label("剂型").click()
        logged_in_page.get_by_label("剂型").fill("口服")
        logged_in_page.get_by_label("品牌").click()
        logged_in_page.get_by_label("品牌").fill("青岛品牌")
        logged_in_page.get_by_label("批准文号").click()
        logged_in_page.get_by_label("批准文号").fill("123123")
        logged_in_page.get_by_label("生产企业", exact=True).click()
        logged_in_page.get_by_text("江中集团有限公司").click()
        logged_in_page.get_by_label("给药途径").click()
        logged_in_page.get_by_label("给药途径").fill("口服")
        logged_in_page.get_by_label("上市许可持有人").click()
        logged_in_page.get_by_label("上市许可持有人").fill("青岛测试用")
        logged_in_page.get_by_label("是否组合产品").click()
        logged_in_page.get_by_text("否", exact=True).click()
        logged_in_page.locator(".ant-input-number-input").first.click()
        logged_in_page.locator(".ant-input-number-input").first.fill("12")
        logged_in_page.get_by_label("整散标志").click()
        logged_in_page.get_by_text("整件", exact=True).click()
        logged_in_page.get_by_label("商品明细").locator("#form_item_isEnable").click()
        logged_in_page.get_by_text("否", exact=True).nth(2).click()
        logged_in_page.locator(
            "div:nth-child(28) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(28) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "12")
        logged_in_page.locator(
            "div:nth-child(29) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(29) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "12")
        logged_in_page.get_by_label("储存条件").click()
        logged_in_page.get_by_label("储存条件").fill("常温")
        logged_in_page.get_by_label("储存类别").click()
        logged_in_page.get_by_title("常温").click()
        logged_in_page.locator(
            "div:nth-child(32) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(32) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "div:nth-child(33) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(33) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "10")
        logged_in_page.get_by_label("税目分类编码").click()
        logged_in_page.get_by_label("税目分类编码").fill("1")
        logged_in_page.get_by_label("税目分类名称").click()
        logged_in_page.get_by_label("税目分类名称").fill("1")
        logged_in_page.locator(
            "div:nth-child(36) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(36) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "div:nth-child(37) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(37) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "10")
        logged_in_page.locator(
            "div:nth-child(38) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(38) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "50")
        logged_in_page.locator(
            "div:nth-child(39) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(39) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "div:nth-child(40) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(40) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "div:nth-child(41) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(41) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "div:nth-child(43) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "div:nth-child(43) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.get_by_label("医保编码").click()
        logged_in_page.get_by_label("医保编码").fill("12345678")
        logged_in_page.get_by_label("执行标准").click()
        logged_in_page.get_by_label("执行标准").fill("国家执行标准")
        logged_in_page.get_by_label("整件ABC").click()
        logged_in_page.get_by_title("A", exact=True).locator("div").click()
        logged_in_page.get_by_label("零件ABC").click()
        logged_in_page.get_by_title("A", exact=True).locator("div").nth(1).click()
        logged_in_page.locator(
            ".zhqc-collapse-container__body > .ant-form > div > div:nth-child(3) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-search").first.click()
        logged_in_page.get_by_text("否", exact=True).nth(4).click()
        logged_in_page.get_by_label("是否拆中包装").click()
        logged_in_page.locator(
            "div:nth-child(3) > .p-2 > .zhqc-collapse-container__body > .ant-form > div > div > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > div:nth-child(3) > div > .ant-select-dropdown > div > .rc-virtual-list > .rc-virtual-list-holder > div > .rc-virtual-list-holder-inner > div > .ant-select-item-option-content").first.click()
        logged_in_page.get_by_label("是否首营").click()
        logged_in_page.locator(
            "div:nth-child(3) > .p-2 > .zhqc-collapse-container__body > .ant-form > div > div:nth-child(2) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > div:nth-child(3) > div > .ant-select-dropdown > div > .rc-virtual-list > .rc-virtual-list-holder > div > .rc-virtual-list-holder-inner > div > .ant-select-item-option-content").first.click()
        logged_in_page.get_by_label("是否贵重药品").click()
        logged_in_page.locator(
            "div:nth-child(3) > .p-2 > .zhqc-collapse-container__body > .ant-form > div > div:nth-child(3) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > div:nth-child(3) > div > .ant-select-dropdown > div > .rc-virtual-list > .rc-virtual-list-holder > div > .rc-virtual-list-holder-inner > div > .ant-select-item-option-content").first.click()
        logged_in_page.get_by_label("特殊药品复方制剂").click()
        logged_in_page.locator(
            "div:nth-child(4) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > div:nth-child(3) > div > .ant-select-dropdown > div > .rc-virtual-list > .rc-virtual-list-holder > div > .rc-virtual-list-holder-inner > div > .ant-select-item-option-content").first.click()
        logged_in_page.get_by_label("是否含兴奋剂").click()
        logged_in_page.locator(
            ".zhqc-collapse-container__body > .ant-form > div > div:nth-child(5) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > div:nth-child(3) > div > .ant-select-dropdown > div > .rc-virtual-list > .rc-virtual-list-holder > div > .rc-virtual-list-holder-inner > div > .ant-select-item-option-content").first.click()
        logged_in_page.locator("form").filter(has_text="近效期天数(天)限销天数(天)").get_by_placeholder(
            "请输入").first.click()
        logged_in_page.locator("form").filter(has_text="近效期天数(天)限销天数(天)").get_by_placeholder(
            "请输入").first.fill("30")
        logged_in_page.locator("form").filter(has_text="近效期天数(天)限销天数(天)").get_by_placeholder("请输入").nth(
            1).click()
        logged_in_page.locator("form").filter(has_text="近效期天数(天)限销天数(天)").get_by_placeholder("请输入").nth(
            1).fill(
            "15")
        logged_in_page.get_by_role("tab", name="商品图片信息").click()
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_skuCode").click()
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_skuCode").fill("123")
        logged_in_page.get_by_role("spinbutton", name="请输入").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").fill("123")
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_skuName").click()
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_skuName").fill("123")
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_spec").click()
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_spec").fill("123")
        logged_in_page.locator(
            "#rc-tabs-2-panel-2 > div > div > .p-2 > .zhqc-collapse-container__body > .ant-form > div > div:nth-child(6) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-affix-wrapper").click()
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_mainUnit").fill("123")
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_approvalNumber").click()
        logged_in_page.get_by_label("商品图片信息").locator("#form_item_approvalNumber").fill("23")
        logged_in_page.get_by_role("textbox", name="生产企业").click()
        logged_in_page.get_by_role("textbox", name="生产企业").fill("123")
        logged_in_page.get_by_role("tab", name="GSP信息").click()
        logged_in_page.get_by_label("双复双验").click()
        logged_in_page.get_by_label("GSP信息").get_by_text("是", exact=True).click()
        logged_in_page.get_by_role("combobox", name="追溯码").click()
        # logged_in_page.get_by_label("追溯码").get_by_text("否", exact=True).click()
        # logged_in_page.get_by_title("否", exact=True).nth(0).click()
        logged_in_page.locator(
            'xpath=//*[@id="rc-tabs-2-panel-3"]/div/div[1]/div[2]/div/form/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div[2]/div[1]/div/div/div[1]/div').click()
        # logged_in_page.get_by_text("否", exact=True).first.click()
        logged_in_page.get_by_label("养护类型").click()
        logged_in_page.get_by_text("一般养护").click()
        logged_in_page.get_by_label("打印药品检验报告").click()
        logged_in_page.get_by_label("GSP信息").get_by_title("否").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").fill("1")
        logged_in_page.get_by_role("button", name="添 加").first.click()
        logged_in_page.get_by_label("证书编号").click()
        logged_in_page.get_by_label("证书编号").fill("QD证书")
        logged_in_page.get_by_label("证书类型").click()
        logged_in_page.get_by_title("GMP证书").click()
        logged_in_page.get_by_label("证书名称").click()
        logged_in_page.get_by_label("证书名称").fill("123")
        logged_in_page.get_by_label("失效日期").click()
        logged_in_page.get_by_text("31", exact=True).click()
        logged_in_page.get_by_role("dialog", name="新增").locator("#form_item_isEnable").click()
        logged_in_page.get_by_role("dialog").get_by_text("是", exact=True).click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="添 加").nth(1).click()
        logged_in_page.get_by_role("dialog", name="新增").locator("#form_item_certificateNo").click()
        logged_in_page.get_by_role("dialog", name="新增").locator("#form_item_certificateNo").fill("123")
        logged_in_page.get_by_role("dialog", name="新增").locator("#form_item_expirationDate").click()
        logged_in_page.get_by_role("cell", name="31", exact=True).locator("div").click()
        logged_in_page.get_by_role("dialog", name="新增").locator("#form_item_isEnable").click()
        logged_in_page.get_by_role("dialog").get_by_text("是", exact=True).click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^耗材$")).first.click()
        logged_in_page.get_by_label("耗材").get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("耗材产品").click()
        logged_in_page.get_by_text("玻璃瓶").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").fill("1")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("tab", name="产品包装数").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("123")
        logged_in_page.locator(".ag-cell").first.click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_business_check_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料", exact=True).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^商品档案$")).click()
        logged_in_page.get_by_text("商品监管信息维护").click()
        logged_in_page.locator("li").filter(has_text="商品监管信息维护").nth(1).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("健胃消食片")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^商品档案$")).click()
        logged_in_page.locator("li").filter(has_text="商品监管信息维护").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_warehouse_container_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.locator("li").filter(has_text="仓储容器资料").nth(1).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("XNRQ")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.get_by_text("仓储容器资料").first.click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="新增容器").click()
        logged_in_page.get_by_label("容器编码").click()
        logged_in_page.get_by_label("容器编码").fill("12315")
        logged_in_page.get_by_label("容器名称").click()
        logged_in_page.get_by_label("容器名称").fill("12315")
        logged_in_page.get_by_label("容器条码").click()
        logged_in_page.get_by_label("容器条码").fill("13251411")
        logged_in_page.get_by_label("容器类型").click()
        logged_in_page.get_by_title("周转箱").locator("div").click()
        logged_in_page.get_by_label("使用状态").click()
        logged_in_page.get_by_text("停用").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("123")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-row-odd > div").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_basic_sildway_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.locator("li").filter(has_text="分拣滑道资料").nth(1).click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        expect(logged_in_page.locator("form")).to_contain_text("拆零复核滑道")
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.locator("li").filter(has_text="分拣滑道资料").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("滑道号").click()
        logged_in_page.get_by_label("滑道号").fill("123")
        logged_in_page.get_by_label("滑道分类").click()
        logged_in_page.get_by_title("换箱上架滑道").click()
        logged_in_page.get_by_label("滑道类别").click()
        logged_in_page.get_by_text("异常剔除口").click()
        logged_in_page.get_by_label("滑道状态").click()
        logged_in_page.get_by_text("停用").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").fill("1")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_label("滑道号").click()
        logged_in_page.get_by_label("滑道号").fill("12")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").nth(2).click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_basic_picking_desk_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.locator("li").filter(has_text="拣货台资料").nth(1).click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        expect(logged_in_page.locator("form")).to_contain_text("通用")
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.locator("li").filter(has_text="拣货台资料").nth(1).click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator("#app").get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("拣货台编号").click()
        logged_in_page.get_by_label("拣货台编号").fill("18")
        logged_in_page.get_by_label("拣货台类型").click()
        logged_in_page.get_by_title("出库").click()
        logged_in_page.get_by_label("是否可用").click()
        logged_in_page.get_by_text("否", exact=True).click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.locator("#app").get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_basic_work_desk_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储设备资料维护$")).click()
        logged_in_page.locator("li").filter(has_text="作业台资料").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("作业台编号").click()
        logged_in_page.get_by_label("作业台编号").fill("testui")
        logged_in_page.get_by_label("作业台名称").click()
        logged_in_page.get_by_label("作业台名称").fill("testui")
        logged_in_page.get_by_label("是否可用").click()
        logged_in_page.get_by_text("否", exact=True).click()
        logged_in_page.get_by_label("作业类型").click()
        logged_in_page.get_by_label("新增").get_by_text("普通复核台").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_label("作业台编号").click()
        logged_in_page.get_by_label("作业台编号").fill("10")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox > .ag-labeled > .ag-wrapper").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_basic_consign_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^托运公司$")).click()
        logged_in_page.locator("li").filter(has_text="托运公司档案").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("托运公司编码").click()
        logged_in_page.get_by_label("托运公司编码").fill("testui1")
        logged_in_page.get_by_label("托运公司名称简称").click()
        logged_in_page.get_by_label("托运公司名称简称").fill("ui")
        logged_in_page.get_by_label("托运公司名称", exact=True).click()
        logged_in_page.get_by_label("托运公司名称", exact=True).fill("testui1")
        logged_in_page.get_by_label("联系人").click()
        logged_in_page.get_by_label("联系人").fill("测试人员")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282391")
        logged_in_page.get_by_label("托运公司电话").click()
        logged_in_page.get_by_label("托运公司电话").fill("18660282391")
        logged_in_page.get_by_label("托运公司地址").click()
        logged_in_page.get_by_label("托运公司地址").fill("山东省青岛市市北区")
        logged_in_page.get_by_label("托运公司类型").click()
        logged_in_page.get_by_title("托运", exact=True).locator("div").click()
        logged_in_page.locator(
            "div:nth-child(12) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_title("ToB").click()
        logged_in_page.get_by_role("button", name="添加行").click()
        logged_in_page.locator("td:nth-child(3) > .vxe-cell").click()
        logged_in_page.get_by_role("cell", name=" 证照类型必须填写").get_by_role("textbox").click()
        logged_in_page.get_by_text("营业执照").click()
        logged_in_page.locator("td:nth-child(4) > .vxe-cell").click()
        logged_in_page.get_by_role("cell", name=" 签订日期必须填写").get_by_role("textbox").click()
        logged_in_page.get_by_text("23", exact=True).click()
        logged_in_page.locator("td:nth-child(5) > .vxe-cell").click()
        logged_in_page.get_by_role("cell", name=" 生效日期必须填写").get_by_role("textbox").click()
        logged_in_page.get_by_text("1", exact=True).nth(3).click()
        logged_in_page.locator("td:nth-child(6) > .vxe-cell").click()
        logged_in_page.get_by_role("cell", name=" 失效日期必须填写").get_by_role("textbox").click()
        logged_in_page.get_by_text("31", exact=True).click()
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("testui")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        expect(logged_in_page.locator("#app")).to_contain_text("托运")
        logged_in_page.locator("div").filter(has_text=re.compile(r"^托运公司$")).click()
        logged_in_page.locator("li").filter(has_text="托运公司档案").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_erp_consign_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^托运公司$")).click()
        logged_in_page.locator("li").filter(has_text="ERP承运商档案").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("承运商来源编码").click()
        logged_in_page.get_by_label("承运商来源编码").fill("testui")
        logged_in_page.get_by_label("承运商编码").click()
        logged_in_page.get_by_label("承运商编码").fill("testui")
        logged_in_page.get_by_label("承运商名称").click()
        logged_in_page.get_by_label("承运商名称").fill("青岛test")
        logged_in_page.get_by_label("联系人").click()
        logged_in_page.get_by_label("联系人").fill("测试人员")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282391")
        logged_in_page.get_by_label("联系地址").click()
        logged_in_page.get_by_label("联系地址").fill("山东省青岛市市北区")
        logged_in_page.get_by_label("承运商类型").click()
        logged_in_page.get_by_label("新增").get_by_text("快递").click()
        logged_in_page.get_by_label("承运商平台").click()
        logged_in_page.get_by_text("淘宝").click()
        logged_in_page.get_by_label("WMS承运商").click()
        logged_in_page.get_by_title("青岛快递").click()
        logged_in_page.get_by_title("WMS", exact=True).click()
        logged_in_page.get_by_label("新增").get_by_text("苍穹ERP").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator("#app").get_by_text("承运商来源编码").click()
        time.sleep(0.5)
        logged_in_page.get_by_placeholder("请输入").first.click()
        logged_in_page.get_by_placeholder("请输入").first.fill("testui")
        logged_in_page.get_by_role("button", name="搜索").click()
        time.sleep(0.5)
        logged_in_page.get_by_label("Press Space to toggle row").check()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_basic_direction_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="方向线路维护").nth(1).click()
        logged_in_page.get_by_text("青岛市内").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="新 增").first.click()
        logged_in_page.get_by_label("配送方向").click()
        logged_in_page.get_by_label("新增").get_by_text("青岛市内").click()
        logged_in_page.get_by_label("线路编号").click()
        logged_in_page.get_by_label("线路编号").fill("testui")
        logged_in_page.get_by_label("线路名称").click()
        logged_in_page.get_by_label("线路名称").fill("testui")
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("100")
        logged_in_page.get_by_label("始发省").click()
        logged_in_page.get_by_title("北京").click()
        logged_in_page.get_by_label("始发市").click()
        logged_in_page.get_by_text("北京市").click()
        logged_in_page.get_by_label("始发位置").click()
        logged_in_page.get_by_label("始发位置").fill("青岛市")
        logged_in_page.get_by_label("目的省").click()
        logged_in_page.get_by_text("北京").nth(4).click()
        logged_in_page.get_by_label("目的市").click()
        logged_in_page.get_by_text("北京市").nth(2).click()
        logged_in_page.get_by_label("目的位置").click()
        logged_in_page.get_by_label("目的位置").fill("青岛")
        time.sleep(0.5)
        logged_in_page.get_by_label("新增").get_by_role("button", name="新 增").click()
        time.sleep(0.5)
        logged_in_page.get_by_label("途径省").click()
        logged_in_page.get_by_text("北京", exact=True).nth(4).click()
        logged_in_page.locator(
            "div:nth-child(2) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-item").click()
        logged_in_page.get_by_text("北京市").nth(4).click()
        logged_in_page.get_by_label("途径位置").click()
        logged_in_page.get_by_label("途径位置").fill("青岛")
        logged_in_page.locator("form").filter(has_text="途径省北京110000120000").get_by_placeholder("请输入").nth(
            3).click()
        logged_in_page.locator("form").filter(has_text="途径省北京110000120000").get_by_placeholder("请输入").nth(
            3).fill("1")
        logged_in_page.get_by_role("button", name="确 认").nth(1).click()
        logged_in_page.get_by_role("button", name="确 认").first.click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("tree")).to_contain_text("青岛市内")

    def test_base_send_out_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="发货信息维护").nth(1).click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("智汇奇策科技有限公司")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="发货信息维护").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").locator("div").click()
        logged_in_page.locator(".ant-select-selection-overflow").first.click()
        logged_in_page.get_by_title("零售事业部").locator("div").click()
        logged_in_page.get_by_label("发货人电话").click()
        logged_in_page.get_by_label("发货人", exact=True).click()
        logged_in_page.get_by_label("发货人", exact=True).fill("测试人员")
        logged_in_page.get_by_label("发货人电话").click()
        logged_in_page.get_by_label("发货人电话").fill("18660282391")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="发货信息维护").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").nth(1).click()

    def test_cart_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="车辆档案维护").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("车牌号").click()
        logged_in_page.get_by_label("车牌号").fill("鲁B1212")
        logged_in_page.get_by_label("助记码").click()
        logged_in_page.get_by_label("助记码").fill("123")
        logged_in_page.get_by_label("所属公司").click()
        logged_in_page.get_by_title("智汇奇策托运公司").locator("div").click()
        logged_in_page.get_by_label("车辆类别").click()
        logged_in_page.get_by_title("冷藏车", exact=True).locator("div").click()
        logged_in_page.get_by_label("车型").click()
        logged_in_page.get_by_label("车型").fill("东风小康")
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("10")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).fill("12")
        logged_in_page.get_by_label("配送方向").click()
        logged_in_page.get_by_title("不分方向").locator("div").click()
        logged_in_page.get_by_label("路线").click()
        logged_in_page.get_by_title("不分线路").locator("div").click()
        logged_in_page.get_by_label("司机").click()
        logged_in_page.get_by_title("大田老江").locator("div").click()
        logged_in_page.get_by_label("车辆状态").click()
        logged_in_page.get_by_title("正常").click()
        logged_in_page.get_by_label("生效日期").click()
        logged_in_page.get_by_title("-10-01").locator("div").click()
        logged_in_page.get_by_label("失效日期").click()
        time.sleep(0.2)
        logged_in_page.get_by_text("31").nth(1).click()
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("鲁B1212")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        expect(logged_in_page.locator("#app")).to_contain_text("默认仓库")
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="车辆档案维护").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_basic_driver_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="基础资料").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="司机档案维护").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("单位名称").click()
        logged_in_page.get_by_title("智汇奇策托运公司").locator("div").click()
        logged_in_page.get_by_label("司机编码").click()
        logged_in_page.get_by_label("司机编码").fill("testui")
        logged_in_page.get_by_label("司机姓名").click()
        logged_in_page.get_by_label("司机姓名").fill("testui")
        logged_in_page.get_by_label("司机驾驶证号").click()
        logged_in_page.get_by_label("司机驾驶证号").fill("123321456123321")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282399")
        logged_in_page.get_by_label("驾驶证生效日期").click()
        logged_in_page.get_by_title("-10-01").locator("div").click()
        logged_in_page.get_by_label("驾驶证失效日期").click()
        time.sleep(0.2)
        logged_in_page.get_by_role("cell", name="31").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_label("司机驾驶证号").click()
        logged_in_page.get_by_label("司机驾驶证号").fill("1233214561213321")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator("form").filter(has_text="仓库默认仓库 单位名称智汇奇策托运公司").get_by_role(
            "button").nth(
            2).click()
        logged_in_page.get_by_label("司机驾驶证号").click()
        logged_in_page.get_by_label("司机驾驶证号").fill("123321123321123456")
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("testui")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^配送相关维护$")).click()
        logged_in_page.locator("li").filter(has_text="司机档案维护").nth(1).click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-wrapper").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
