import pytest
import re
from playwright.sync_api import sync_playwright, Page, expect
import time
from other_utils import *
import asyncio


@pytest.fixture(scope="class")
def browser_context():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)  # 可视化模式
        context = browser.new_context(
            viewport={"width": 1920, "height": 1080}
        )
        yield context
        # context.close()
        # browser.close()


@pytest.fixture(scope="class")
def logged_in_page(browser_context) -> Page:
    page = browser_context.new_page()
    page.goto(
        "http://192.168.111.232:18901/login?haveWarehouse=1&client_id=iowtb-new&redirect_uri=http://192.168.111.232:9832/login")
    page.get_by_placeholder("请输入账号").click()
    page.get_by_placeholder("请输入账号").fill("ssoadmintest6")
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").fill("lhx7758521")
    page.locator("#warehouse").select_option("1")
    page.get_by_role("button", name="登录").click()
    expect(page.locator("header")).to_contain_text("首页")
    yield page
    # page.close()


class TestOrderPage:
    erp_order_no = f"ui-test{generate_random_number()}"
    toc_order_no = f"ui-test{generate_random_number()}"

    def test_in_order_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("订单管理").click()
        logged_in_page.locator("li").filter(has_text="入库订单").first.click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("业务单号").click()
        logged_in_page.get_by_label("业务单号").fill(f"test-20241023010")
        logged_in_page.get_by_label("订单类型").click()
        logged_in_page.get_by_title("采购订单", exact=True).locator("div").click()
        logged_in_page.get_by_label("货主", exact=True).click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").locator("div").click()
        logged_in_page.get_by_label("供应商").click()
        logged_in_page.get_by_text("青岛医药科技集团有限公司--智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("产品类型").click()
        logged_in_page.get_by_title("药品").locator("div").click()
        logged_in_page.get_by_label("采购单号").click()
        logged_in_page.get_by_label("采购单号").fill("ui")
        logged_in_page.get_by_label("业务单号").click()
        logged_in_page.get_by_label("业务单号").dblclick()
        logged_in_page.get_by_label("业务单号").fill(TestOrderPage.erp_order_no)
        logged_in_page.get_by_role("button", name="添加明细").click()
        logged_in_page.get_by_label("产品", exact=True).click()
        logged_in_page.get_by_label("产品", exact=True).fill("氨糖")
        logged_in_page.get_by_text("氨糖--50g--智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("货权组织").click()
        logged_in_page.get_by_label("新增").get_by_text("零售事业部").click()
        logged_in_page.get_by_label("新增").locator("#form_item_supplierId").click()
        logged_in_page.get_by_label("新增").get_by_text("青岛医药科技集团有限公司--智汇奇策科技有限公司").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("10.111")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).fill("1.111")
        logged_in_page.get_by_label("管理效期天数").click()
        logged_in_page.get_by_label("管理效期天数").fill("30")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        expect(logged_in_page.locator("#app")).to_contain_text("ui")
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        expect(logged_in_page.locator("form")).to_contain_text("采购订单")

    def test_out_order_tob_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("订单管理").click()
        logged_in_page.locator("li").filter(has_text="出库订单").first.click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("产品表单类型").click()
        logged_in_page.get_by_title("药品").click()
        logged_in_page.get_by_label("WMS业务类型").click()
        logged_in_page.get_by_text("ToB").click()
        logged_in_page.get_by_label("ERP订单号").click()
        logged_in_page.get_by_label("ERP订单号").fill(TestOrderPage.erp_order_no)
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").locator("div").click()
        logged_in_page.get_by_label("货权组织").click()
        logged_in_page.get_by_title("零售事业部").locator("div").click()
        logged_in_page.get_by_label("订单类型").click()
        logged_in_page.get_by_title("网店发货单").locator("div").click()
        logged_in_page.get_by_label("合作伙伴类型").click()
        logged_in_page.get_by_title("店铺", exact=True).click()
        logged_in_page.get_by_label("合作伙伴", exact=True).click()
        logged_in_page.get_by_title("青岛漱玉平民大药房台东店").locator("div").click()
        logged_in_page.get_by_label("承运商").click()
        logged_in_page.get_by_title("苍穹运输商").click()
        logged_in_page.get_by_label("提货方式").click()
        logged_in_page.get_by_title("自配送").click()
        logged_in_page.get_by_label("联系人").click()
        logged_in_page.get_by_label("联系人").fill("测试人员")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282391")
        logged_in_page.get_by_label("省").click()
        logged_in_page.get_by_text("北京").click()
        logged_in_page.get_by_label("市").click()
        logged_in_page.get_by_text("北京市").click()
        logged_in_page.get_by_label("区", exact=True).click()
        logged_in_page.get_by_text("东城区").nth(1).click()
        logged_in_page.get_by_label("联系地址").click()
        logged_in_page.get_by_label("联系地址").fill("山东省青岛市市北区昆明路")
        logged_in_page.get_by_label("是否处方药").click()
        logged_in_page.get_by_text("否", exact=True).click()
        logged_in_page.get_by_label("打印上游随货同行").click()
        logged_in_page.get_by_text("否").nth(2).click()
        logged_in_page.get_by_label("打印上游发票").click()
        logged_in_page.get_by_text("否", exact=True).nth(4).click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("ui自动化测试数据")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("产品", exact=True).click()
        logged_in_page.get_by_label("产品", exact=True).fill("氨糖")
        logged_in_page.get_by_text("氨糖--50g--智汇奇策科技有限公司").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("1.111")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).fill("100")
        logged_in_page.get_by_label("生产批号").click()
        logged_in_page.get_by_label("生产批号").fill("20240910001")
        logged_in_page.get_by_label("库存状态").click()
        logged_in_page.get_by_text("合格", exact=True).click()
        logged_in_page.get_by_text("日期", exact=True).first.click()
        logged_in_page.get_by_text("月份", exact=True).click()
        logged_in_page.get_by_label("生产日期", exact=True).click()
        logged_in_page.get_by_text("1月", exact=True).dblclick()
        logged_in_page.locator("span").filter(has_text=re.compile(r"^日期$")).click()
        logged_in_page.get_by_text("月份").nth(3).click()
        logged_in_page.get_by_role("textbox", name="* 有效期至").click()
        logged_in_page.get_by_role("cell", name="12月").locator("div").click()
        logged_in_page.get_by_label("限制效期").click()
        logged_in_page.get_by_text("不限制").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        expect(logged_in_page.locator("form")).to_contain_text("WMS")
        logged_in_page.locator("li").filter(has_text="出库订单").first.click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("网店发货单")
        expect(logged_in_page.get_by_role("grid")).to_contain_text(TestOrderPage.erp_order_no)
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="生成SO").click()

    def test_out_order_toc_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.get_by_text("订单管理").click()
        logged_in_page.locator("li").filter(has_text="出库订单").first.click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("产品表单类型").click()
        logged_in_page.get_by_title("药品").click()
        logged_in_page.get_by_label("WMS业务类型").click()
        logged_in_page.get_by_text("ToC").click()
        logged_in_page.get_by_label("ERP订单号").click()
        logged_in_page.get_by_label("ERP订单号").fill(TestOrderPage.toc_order_no)
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").locator("div").click()
        logged_in_page.get_by_label("货权组织").click()
        logged_in_page.get_by_title("零售事业部").locator("div").click()
        logged_in_page.get_by_label("订单类型").click()
        logged_in_page.get_by_title("网店发货单").locator("div").click()
        logged_in_page.get_by_label("合作伙伴类型").click()
        logged_in_page.get_by_title("店铺", exact=True).click()
        logged_in_page.get_by_label("合作伙伴", exact=True).click()
        logged_in_page.get_by_title("青岛漱玉平民大药房台东店").locator("div").click()
        logged_in_page.get_by_label("承运商").click()
        logged_in_page.get_by_title("苍穹运输商").click()
        logged_in_page.get_by_label("提货方式").click()
        logged_in_page.get_by_title("自配送").click()
        logged_in_page.get_by_label("联系人").click()
        logged_in_page.get_by_label("联系人").fill("测试人员")
        logged_in_page.get_by_label("联系电话").click()
        logged_in_page.get_by_label("联系电话").fill("18660282391")
        logged_in_page.get_by_label("省").click()
        logged_in_page.get_by_text("北京").click()
        logged_in_page.get_by_label("市").click()
        logged_in_page.get_by_text("北京市").click()
        logged_in_page.get_by_label("区", exact=True).click()
        logged_in_page.get_by_text("东城区").nth(1).click()
        logged_in_page.get_by_label("联系地址").click()
        logged_in_page.get_by_label("联系地址").fill("山东省青岛市市北区昆明路")
        logged_in_page.get_by_label("是否处方药").click()
        logged_in_page.get_by_text("否", exact=True).click()
        logged_in_page.get_by_label("打印上游随货同行").click()
        logged_in_page.get_by_text("否").nth(2).click()
        logged_in_page.get_by_label("打印上游发票").click()
        logged_in_page.get_by_text("否", exact=True).nth(4).click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("ui自动化测试数据")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("产品", exact=True).click()
        logged_in_page.get_by_label("产品", exact=True).fill("氨糖")
        logged_in_page.get_by_text("氨糖--50g--智汇奇策科技有限公司").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("1.111")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).fill("100")
        logged_in_page.get_by_label("生产批号").click()
        logged_in_page.get_by_label("生产批号").fill("20240910001")
        logged_in_page.get_by_label("库存状态").click()
        logged_in_page.get_by_text("合格", exact=True).click()
        logged_in_page.get_by_text("日期", exact=True).first.click()
        logged_in_page.get_by_text("月份", exact=True).click()
        logged_in_page.get_by_label("生产日期", exact=True).click()
        logged_in_page.get_by_text("1月", exact=True).dblclick()
        logged_in_page.locator("span").filter(has_text=re.compile(r"^日期$")).click()
        logged_in_page.get_by_text("月份").nth(3).click()
        logged_in_page.get_by_role("textbox", name="* 有效期至").click()
        logged_in_page.get_by_role("cell", name="12月").locator("div").click()
        logged_in_page.get_by_label("限制效期").click()
        logged_in_page.get_by_text("不限制").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        expect(logged_in_page.locator("form")).to_contain_text("WMS")
        logged_in_page.locator("li").filter(has_text="出库订单").first.click()
        expect(logged_in_page.get_by_role("grid")).to_contain_text("网店发货单")
        expect(logged_in_page.get_by_role("grid")).to_contain_text(TestOrderPage.toc_order_no)
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="生成SO").click()
