import pytest
import re
from playwright.sync_api import sync_playwright, Page, expect
import time
from other_utils import *
import asyncio


@pytest.fixture(scope="class")
def browser_context():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)  # 可视化模式
        context = browser.new_context(
            viewport={"width": 1920, "height": 1080}
        )
        yield context
        # context.close()
        # browser.close()


@pytest.fixture(scope="class")
def logged_in_page(browser_context) -> Page:
    page = browser_context.new_page()
    page.goto(
        "http://192.168.111.232:18901/login?haveWarehouse=1&client_id=iowtb-new&redirect_uri=http://192.168.111.232:9832/login")
    page.get_by_placeholder("请输入账号").click()
    page.get_by_placeholder("请输入账号").fill("ssoadmintest6")
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").fill("lhx7758521")
    page.locator("#warehouse").select_option("1")
    page.get_by_role("button", name="登录").click()
    expect(page.locator("header")).to_contain_text("首页")
    yield page
    # page.close()


class TestSettlementManagementUi:

    def test_business_type_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^基础资料$")).click()
        logged_in_page.locator("li").filter(has_text="业务类型").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("业务类型编码").click()
        logged_in_page.get_by_label("业务类型编码").fill("testui")
        logged_in_page.get_by_label("业务类型名称").click()
        logged_in_page.get_by_label("业务类型名称").fill("ui测试用")
        logged_in_page.get_by_label("所属业务").click()
        logged_in_page.get_by_title("仓储").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_placeholder("请输入").nth(1).click()
        logged_in_page.get_by_placeholder("请输入").nth(1).fill("UI测试用")
        logged_in_page.get_by_role("button", name="搜索").click()
        expect(logged_in_page.get_by_role("gridcell", name="testui")).to_be_visible()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_business_service_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^基础资料$")).click()
        logged_in_page.locator("li").filter(has_text="服务项").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("服务编码").click()
        logged_in_page.get_by_label("服务编码").fill("testui")
        logged_in_page.get_by_label("服务名称").click()
        logged_in_page.get_by_label("服务名称").fill("UI测试用")
        logged_in_page.get_by_label("业务类别").click()
        logged_in_page.get_by_title("仓储").click()
        logged_in_page.locator(
            "div:nth-child(4) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-item").click()
        logged_in_page.get_by_title("仓储成本").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_placeholder("请输入").nth(1).click()
        logged_in_page.get_by_placeholder("请输入").nth(1).fill("UI测试用")
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        expect(logged_in_page.get_by_role("gridcell", name="UI测试用").first).to_be_visible()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_business_price_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^基础资料$")).click()
        logged_in_page.locator("li").filter(has_text="费用项").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("费用编码").click()
        logged_in_page.get_by_label("费用编码").fill("testui")
        logged_in_page.get_by_label("费用编码").press("Tab")
        logged_in_page.get_by_role("textbox", name="* 费用项").fill("UI测试用")
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("入库").click()
        logged_in_page.get_by_label("收付类型").click()
        logged_in_page.get_by_title("应收应付").click()
        logged_in_page.get_by_label("免税").click()
        logged_in_page.get_by_title("否").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").fill("1")
        logged_in_page.get_by_label("参与利润").click()
        logged_in_page.get_by_title("否").nth(2).click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).fill("UI测试用")
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_contract_receivable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^合同管理$")).click()
        logged_in_page.locator("li").filter(has_text="应收合同").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        time.sleep(1)
        logged_in_page.get_by_label("合同名称").click()
        logged_in_page.get_by_label("合同名称").fill("testui")
        logged_in_page.get_by_label("合同类型").click()
        logged_in_page.get_by_title("仓储服务合同").click()
        logged_in_page.get_by_label("甲方类型").click()
        logged_in_page.get_by_title("货主").first.click()
        logged_in_page.get_by_role("combobox", name="* 货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("甲方联系人").click()
        logged_in_page.get_by_label("甲方联系人").fill("测试人员")
        logged_in_page.get_by_label("甲方联系方式").click()
        logged_in_page.get_by_label("甲方联系方式").fill("18660282391")
        logged_in_page.get_by_label("甲方联系邮箱").click()
        logged_in_page.get_by_label("甲方联系邮箱").fill("111111@qq.com")
        logged_in_page.locator(
            "div:nth-child(12) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-input-affix-wrapper").click()
        logged_in_page.get_by_label("业主联系人").click()
        logged_in_page.get_by_label("业主联系人").fill("测试人员")
        logged_in_page.get_by_label("业主联系方式").click()
        logged_in_page.get_by_label("业主联系方式").fill("18660282392")
        logged_in_page.get_by_label("业主联系邮箱").click()
        logged_in_page.get_by_label("业主联系邮箱").fill("22222@qq.com")
        logged_in_page.get_by_label("结算周期").click()
        logged_in_page.get_by_title("日结").click()
        logged_in_page.get_by_label("签署日期").click()
        logged_in_page.get_by_title("-10-01").locator("div").click()
        logged_in_page.get_by_label("生效日期").click()
        logged_in_page.get_by_role("table").get_by_title("-10-02").nth(1).click()
        logged_in_page.get_by_label("失效日期").click()
        logged_in_page.get_by_role("cell", name="31").nth(1).click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("测试人员")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).fill("testui")
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_contract_payable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^合同管理$")).click()
        logged_in_page.locator("li").filter(has_text="应付合同").nth(1).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("合同名称").click()
        logged_in_page.get_by_label("合同名称").fill("testui")
        logged_in_page.get_by_label("业主联系人").click()
        logged_in_page.get_by_label("业主联系人").fill("测试人员")
        logged_in_page.get_by_label("业主联系方式").click()
        logged_in_page.get_by_label("业主联系方式").fill("18660282391")
        logged_in_page.get_by_label("业主联系邮箱").click()
        logged_in_page.get_by_label("业主联系邮箱").fill("111111@qq.com")
        logged_in_page.get_by_label("供应商").click()
        logged_in_page.get_by_title("青岛医药科技集团有限公司--智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("乙方联系人").click()
        logged_in_page.get_by_label("乙方联系人").fill("测试人员")
        logged_in_page.get_by_label("乙方联系方式").click()
        logged_in_page.get_by_label("乙方联系方式").fill("18660282392")
        logged_in_page.get_by_label("乙方联系邮箱").click()
        logged_in_page.get_by_label("乙方联系邮箱").fill("22222@qq.com")
        logged_in_page.get_by_label("结算周期").click()
        logged_in_page.get_by_title("日结").click()
        logged_in_page.get_by_label("签署日期").click()
        logged_in_page.get_by_title("-10-01").click()
        logged_in_page.get_by_label("生效日期").click()
        logged_in_page.get_by_role("table").get_by_title("-10-02").nth(1).click()
        logged_in_page.get_by_label("失效日期").click()
        logged_in_page.get_by_role("cell", name="31").nth(1).click()
        logged_in_page.get_by_label("合同备注").click()
        logged_in_page.get_by_label("合同备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).fill("testui")
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="批量删除").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_transfer_payable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^协议管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^运输协议$")).click()
        logged_in_page.locator("li").filter(has_text="运输应收计费协议").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("合同名称").click()
        logged_in_page.get_by_title("与智汇奇策公司的运输合同").click()
        logged_in_page.get_by_label("协议名称").click()
        logged_in_page.get_by_label("协议名称").fill("UI测试用")
        logged_in_page.get_by_label("协议名称").press("Enter")
        logged_in_page.get_by_label("协议简称").click()
        logged_in_page.get_by_label("协议简称").fill("UI测试用")
        logged_in_page.locator("div").filter(has_text=re.compile(r"^备注$")).nth(2).click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("运输成本").click()
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("店铺运输成本").click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("店铺运输费用").click()
        logged_in_page.get_by_label("始发省").click()
        logged_in_page.get_by_title("北京").click()
        logged_in_page.get_by_label("始发市").click()
        logged_in_page.get_by_title("北京市").click()
        logged_in_page.get_by_label("始发区").click()
        logged_in_page.get_by_title("东城区").nth(1).click()
        logged_in_page.locator(".ant-select-selection-overflow").click()
        logged_in_page.locator(".ant-select-tree-checkbox-inner").first.click()
        logged_in_page.get_by_label("物品类型").click()
        logged_in_page.get_by_title("文件").click(button="right")
        logged_in_page.get_by_text("文件").click()
        logged_in_page.get_by_label("时效等级").click()
        logged_in_page.get_by_title("次日达").click()
        logged_in_page.get_by_label("是否出账").click()
        logged_in_page.get_by_title("是", exact=True).click()
        logged_in_page.get_by_label("运输方式").click()
        logged_in_page.get_by_title("市内配送").click()
        logged_in_page.get_by_label("运输类型").click()
        logged_in_page.get_by_title("配送", exact=True).click()
        logged_in_page.get_by_label("对比公式").click()
        logged_in_page.get_by_title("=", exact=True).click()
        logged_in_page.get_by_label("重泡").click()
        logged_in_page.get_by_label("重泡").fill("1")
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按票").click(button="right")
        logged_in_page.get_by_text("按票").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("票", exact=True).click()
        logged_in_page.get_by_label("固定金额").check()
        logged_in_page.get_by_label("币别").click()
        logged_in_page.get_by_title("人民币").click()
        logged_in_page.get_by_label("金额单位").click()
        logged_in_page.get_by_title("元").click()
        logged_in_page.get_by_label("计费阶梯方式").click()
        logged_in_page.get_by_title("单区间").click()
        logged_in_page.get_by_label("保留小数").click()
        logged_in_page.get_by_title("2位").click()
        logged_in_page.get_by_label("新增").get_by_role("button", name="新 增").click()
        logged_in_page.locator(".ant-input-number-input").first.click()
        logged_in_page.locator(".ant-input-number-input").first.fill("0")
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "100")
        logged_in_page.locator(
            "td:nth-child(4) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(4) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "10")
        logged_in_page.get_by_text("保存").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_transport_cost_settlement_management_ui(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^协议管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^运输协议$")).click()
        logged_in_page.locator("li").filter(has_text="运输应付计费协议").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("协议名称").click()
        logged_in_page.get_by_label("协议名称").fill("UI测试用")
        logged_in_page.get_by_label("协议简称").click()
        logged_in_page.get_by_label("协议简称").fill("UI测试用")
        logged_in_page.get_by_label("合同名称").click()
        logged_in_page.get_by_title("与智汇奇策公司的运输应付合同").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("运输成本").click()
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("店铺运输成本").click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("店铺运输费用").click()
        logged_in_page.get_by_label("始发省").click()
        logged_in_page.get_by_title("北京").click()
        logged_in_page.get_by_label("始发市").click()
        logged_in_page.get_by_title("北京市").click()
        logged_in_page.get_by_label("始发区").click()
        logged_in_page.get_by_title("东城区").nth(1).click()
        logged_in_page.locator(".ant-select-selection-overflow").click()
        logged_in_page.locator(".ant-select-tree-checkbox-inner").first.click()
        logged_in_page.get_by_label("物品类型").click()
        logged_in_page.get_by_title("文件").click()
        logged_in_page.get_by_label("时效等级").click()
        logged_in_page.get_by_title("次日达").click()
        logged_in_page.get_by_label("是否出账").click()
        logged_in_page.get_by_title("否", exact=True).click()
        logged_in_page.get_by_label("运输方式").click()
        logged_in_page.get_by_title("市内配送").click()
        logged_in_page.get_by_label("运输类型").click()
        logged_in_page.get_by_title("配送", exact=True).click()
        logged_in_page.get_by_label("对比公式").click()
        logged_in_page.get_by_title("=", exact=True).click()
        logged_in_page.get_by_label("重泡").click()
        logged_in_page.get_by_label("重泡").fill("1")
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按票").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("票", exact=True).click()
        logged_in_page.get_by_label("固定金额").check()
        logged_in_page.get_by_label("币别").click()
        logged_in_page.get_by_title("人民币").click()
        logged_in_page.get_by_label("金额单位").click()
        logged_in_page.get_by_title("元").click()
        logged_in_page.get_by_label("计费阶梯方式").click()
        logged_in_page.get_by_title("单区间").click()
        logged_in_page.get_by_label("保留小数").click()
        logged_in_page.get_by_title("2位").click()
        logged_in_page.get_by_label("新增").get_by_role("button", name="新 增").click()
        logged_in_page.locator(".ant-input-number-input").first.click()
        logged_in_page.locator(".ant-input-number-input").first.fill("0")
        logged_in_page.get_by_role("cell", name="Increase Value Decrease Value", exact=True).first.click()
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "")
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "100")
        logged_in_page.locator(
            "td:nth-child(4) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(4) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-handler-wrap > span").first.click()
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.get_by_text("保存").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_warehouse_able_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^协议管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储协议$")).click()
        logged_in_page.locator("li").filter(has_text="仓储应收计费协议").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("协议名称").click()
        logged_in_page.get_by_label("协议名称").fill("UI测试用")
        logged_in_page.get_by_label("合同编号").click()
        logged_in_page.get_by_title("RHT2024082106   与智汇奇策公司的仓储合同").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("一般入库").click()
        logged_in_page.get_by_label("计费触发方式").click()
        logged_in_page.get_by_title("即时计算").click()
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按体积").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("按立方厘米").click()
        logged_in_page.get_by_label("库存计费级别").click()
        logged_in_page.get_by_title("按商品").click()
        logged_in_page.get_by_label("币别").click()
        logged_in_page.get_by_title("人民币").click()
        logged_in_page.get_by_label("金额单位").click()
        logged_in_page.get_by_title("元").click()
        logged_in_page.get_by_label("计费阶梯方式").click()
        logged_in_page.get_by_title("单区间").click()
        logged_in_page.get_by_label("新增").get_by_role("button", name="新 增").click()
        logged_in_page.locator(".ant-input-number-input").first.click()
        logged_in_page.locator(".ant-input-number-input").first.fill("0")
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "100")
        logged_in_page.locator(
            ".ant-table-cell > div > .ant-select > .ant-select-selector > .ant-select-selection-item").click()
        logged_in_page.get_by_title("总价").click()
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "100")
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "10")
        logged_in_page.locator(
            "td:nth-child(7) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(7) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1000")
        logged_in_page.get_by_text("保存").click()
        logged_in_page.get_by_label("新增").get_by_role("textbox", name="请输入").click()
        logged_in_page.get_by_label("新增").get_by_role("textbox", name="请输入").fill("UI测试用")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).fill("UI测试用")
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator("#app").get_by_role("button", name="查看").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.locator("#app").get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()

    def test_warehouse_payable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^协议管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^仓储协议$")).click()
        logged_in_page.locator("li").filter(has_text="仓储应付计费协议").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("协议名称").click()
        logged_in_page.get_by_label("协议名称").fill("UI测试用")
        logged_in_page.get_by_label("合同编号").click()
        logged_in_page.get_by_title("RHT2024082108").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("一般入库").click()
        logged_in_page.get_by_label("计费触发方式").click()
        logged_in_page.get_by_title("即时计算").click()
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按体积").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("按立方厘米").click()
        logged_in_page.get_by_label("库存计费级别").click()
        logged_in_page.get_by_title("按商品").click()
        logged_in_page.get_by_label("币别").click()
        logged_in_page.get_by_title("人民币").click()
        logged_in_page.get_by_label("金额单位").click()
        logged_in_page.get_by_title("元").click()
        logged_in_page.get_by_label("计费阶梯方式").click()
        logged_in_page.get_by_title("单区间").click()
        logged_in_page.get_by_label("新增").get_by_role("button", name="新 增").click()
        logged_in_page.locator(".ant-input-number-input").first.click()
        logged_in_page.locator(".ant-input-number-input").first.fill("0")
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(3) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "100")
        logged_in_page.locator(
            ".ant-table-cell > div > .ant-select > .ant-select-selector > .ant-select-selection-item").click()
        logged_in_page.get_by_title("总价").click()
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(5) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").click()
        logged_in_page.locator(
            "td:nth-child(6) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1")
        logged_in_page.locator("td:nth-child(7) > div > .ant-input-number").click()
        logged_in_page.locator(
            "td:nth-child(7) > div > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input").fill(
            "1000")
        logged_in_page.get_by_text("保存").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator("#app").get_by_role("button", name="查看").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).click()
        logged_in_page.get_by_role("textbox", name="请输入").nth(1).fill("UI测试用")
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.locator("#app").get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()

    def test_cost_management_warehouse_receivable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理-应收费用$")).click()
        logged_in_page.locator("li").filter(has_text="应收费用-仓储").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("结算方式").click()
        logged_in_page.get_by_title("现结").click()
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("青岛啤酒有限公司").click()
        logged_in_page.locator(".ant-form-item-control-input-content > .ant-picker").first.click()
        logged_in_page.get_by_role("cell", name="1", exact=True).first.click()
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("仓储成本").click()
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("库存费").click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("库存费用").click()
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按体积").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("按立方厘米").click()
        logged_in_page.get_by_label("计费条件").click()
        logged_in_page.get_by_title("计费数量").first.click()
        logged_in_page.get_by_role("textbox", name="* 计费数量").click()
        logged_in_page.get_by_role("textbox", name="* 计费数量").fill("100")
        logged_in_page.get_by_label("计费单价").click()
        logged_in_page.get_by_label("计费单价").fill("1")
        logged_in_page.get_by_label("新增").locator("div").filter(has_text=re.compile(r"^请选择$")).nth(4).click()
        logged_in_page.get_by_label("新增").locator("div").filter(has_text=re.compile(r"^金额单位$")).click()
        logged_in_page.get_by_label("是否免税").click()
        logged_in_page.get_by_title("否", exact=True).click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="审 核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="激 活").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_cost_delivery_receivable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理$")).click()
        logged_in_page.get_by_text("费用管理-应收费用").click()
        logged_in_page.locator("li").filter(has_text="应收费用-配送").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("结算方式").click()
        logged_in_page.get_by_title("现结").click()
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("承运商").click()
        logged_in_page.get_by_label("承运商").click()
        logged_in_page.get_by_title("智汇奇策托运公司").click()
        logged_in_page.locator(".ant-form-item-control-input-content > .ant-picker").first.click()
        logged_in_page.get_by_role("cell", name="1", exact=True).first.click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("运输成本").click()
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("店铺运输成本").click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("店铺运输费用").click()
        logged_in_page.get_by_label("配送点数量").click()
        logged_in_page.get_by_label("配送点数量").fill("10")
        logged_in_page.get_by_label("每配送点基础费").click()
        logged_in_page.get_by_label("每配送点基础费").fill("1")
        logged_in_page.get_by_label("配送点摊销费").click()
        logged_in_page.get_by_label("配送点摊销费").fill("1")
        logged_in_page.get_by_label("每包裹计费").click()
        logged_in_page.get_by_label("每包裹计费").fill("1")
        logged_in_page.get_by_label("总箱数").click()
        logged_in_page.get_by_label("总箱数").fill("10")
        logged_in_page.get_by_label("SO单号").click()
        logged_in_page.get_by_label("SO单号").fill("SO123321123123")
        logged_in_page.get_by_label("SO类型").click()
        logged_in_page.get_by_title("网店发货单").click()
        logged_in_page.get_by_label("erp订单号").click()
        logged_in_page.get_by_label("erp订单号").fill("sadsadsa")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="审 核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="取消审核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="作 废").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_cost_warehouse_payable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理-应付费用$")).click()
        logged_in_page.locator("li").filter(has_text="应付费用-仓储").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("结算方式").click()
        logged_in_page.get_by_title("现结").click()
        logged_in_page.get_by_label("供应商").click()
        logged_in_page.get_by_title("青岛医药科技集团有限公司--智汇奇策科技有限公司").click()
        logged_in_page.locator(".ant-picker").first.click()
        logged_in_page.get_by_title("-10-01").locator("div").click()
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("仓储成本").click()
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("库存费").click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("库存费用").click()
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按体积").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("按立方厘米").click()
        logged_in_page.get_by_label("计费条件").click()
        logged_in_page.get_by_title("计费数量").first.click()
        logged_in_page.get_by_role("textbox", name="* 计费数量").click()
        logged_in_page.get_by_role("textbox", name="* 计费数量").fill("10")
        logged_in_page.get_by_label("计费单价").click()
        logged_in_page.get_by_label("计费单价").fill("10")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_label("是否免税").click()
        logged_in_page.get_by_title("否", exact=True).click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="审 核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="取消审核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="作 废").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_cost_delivery_payable_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理-应付费用$")).click()
        logged_in_page.locator("li").filter(has_text="应付费用-配送").nth(2).click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("结算方式").click()
        logged_in_page.get_by_title("现结").click()
        logged_in_page.get_by_label("客户").click()
        logged_in_page.get_by_title("青岛测试客户").click()
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("事业部").click()
        logged_in_page.get_by_title("零售事业部").click()
        logged_in_page.get_by_label("承运商").click()
        logged_in_page.get_by_title("智汇奇策托运公司").click()
        logged_in_page.get_by_label("业务日期").click()
        logged_in_page.get_by_title("-10-01").locator("div").click()
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("运输成本").click()
        logged_in_page.get_by_label("服务项").click()
        logged_in_page.get_by_title("店铺运输成本").click()
        logged_in_page.get_by_label("费用项").click()
        logged_in_page.get_by_title("店铺运输费用").click()
        logged_in_page.get_by_label("计费方式").click()
        logged_in_page.get_by_title("按票").click()
        logged_in_page.get_by_label("计量单位").click()
        logged_in_page.get_by_title("票", exact=True).click()
        logged_in_page.get_by_label("计费数量").click()
        logged_in_page.get_by_label("计费数量").fill("10")
        logged_in_page.get_by_label("计费单价").click()
        logged_in_page.get_by_label("计费单价").fill("1")
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="审 核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="取消审核").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="作 废").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_cost_warehouse_hand_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="结算管理").click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理$")).click()
        logged_in_page.locator("div").filter(has_text=re.compile(r"^费用管理-手动结算$")).click()
        logged_in_page.locator("li").filter(has_text="手动结算-仓储").nth(2).click()
        logged_in_page.get_by_role("tab", name="出库订单").click()
        logged_in_page.get_by_role("tab", name="加工单").click()
        logged_in_page.get_by_role("tab", name="追溯码").click()
        logged_in_page.get_by_role("tab", name="库存").click()
        logged_in_page.get_by_role("tab", name="入库订单").click()
        logged_in_page.get_by_role("button", name="reload 重置").click()
        logged_in_page.get_by_role("button", name="search 搜索").click()
