import pytest
import re
from playwright.sync_api import sync_playwright, Page, expect
import time
from other_utils import *
import asyncio


@pytest.fixture(scope="class")
def browser_context():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)  # 可视化模式
        context = browser.new_context(
            viewport={"width": 1920, "height": 1080}
        )
        yield context
        # context.close()
        # browser.close()


@pytest.fixture(scope="class")
def logged_in_page(browser_context) -> Page:
    page = browser_context.new_page()
    page.goto(
        "http://192.168.111.232:18901/login?haveWarehouse=1&client_id=iowtb-new&redirect_uri=http://192.168.111.232:9832/login")
    page.get_by_placeholder("请输入账号").click()
    page.get_by_placeholder("请输入账号").fill("ssoadmintest6")
    page.get_by_placeholder("请输入密码").click()
    page.get_by_placeholder("请输入密码").fill("lhx7758521")
    page.locator("#warehouse").select_option("1")
    page.get_by_role("button", name="登录").click()
    expect(page.locator("header")).to_contain_text("首页")
    yield page
    # page.close()


class TestProcessUi:

    def test_process_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="流程策略").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_process_print_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="打印分配策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("打印分配策略名称").click()
        logged_in_page.get_by_label("打印分配策略名称").fill("UI测试用")
        logged_in_page.get_by_label("是否启用").click()
        logged_in_page.get_by_title("停用").click()
        logged_in_page.locator(".ant-select-selection-overflow").first.click()
        logged_in_page.get_by_title("网店发货单").click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_title("ToB").click()
        logged_in_page.locator(
            "div:nth-child(6) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-overflow").click()
        logged_in_page.get_by_title("药品批发企业").click()
        logged_in_page.get_by_label("客户", exact=True).click()
        logged_in_page.get_by_title("青岛测试客户").click()
        logged_in_page.get_by_label("文档投递柜").click()
        logged_in_page.get_by_title("柜A").click()
        logged_in_page.get_by_label("起始格口号").click()
        logged_in_page.get_by_label("起始格口号").fill("1")
        logged_in_page.get_by_label("终止格口号").click()
        logged_in_page.get_by_label("终止格口号").fill("2")
        logged_in_page.get_by_label("打印优先级").click()
        logged_in_page.get_by_title("1").nth(3).click()
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("新增").get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("新增").get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="取 消").first.click()

    def test_process_put_shelf_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="上架策略").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()

    def test_yh_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="养护策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("业务类型").click()
        logged_in_page.get_by_label("新增").get_by_text("一般养护").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").fill("1")
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="保 存").click()

    def test_zz_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="周转策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("策略编码").click()
        logged_in_page.get_by_label("策略编码").fill("testui1")
        logged_in_page.get_by_label("策略名称").click()
        logged_in_page.get_by_label("策略名称").fill("UI测试用")
        logged_in_page.get_by_title("启用", exact=True).click()
        logged_in_page.get_by_title("停用").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新增", exact=True).click()
        logged_in_page.locator("td:nth-child(3) > .vxe-cell").click()
        logged_in_page.get_by_role("cell", name=" 批次属性必须填写").get_by_role("textbox").click()
        logged_in_page.get_by_text("生产批号").click()
        logged_in_page.locator("td:nth-child(4) > .vxe-cell").click()
        logged_in_page.get_by_role("cell", name="  优先级必须填写").get_by_role("textbox").click()
        logged_in_page.get_by_role("cell", name="  优先级必须填写").get_by_role("textbox").fill("1")
        logged_in_page.locator("td:nth-child(6) > .vxe-cell").click()
        logged_in_page.get_by_role("row", name=" 1 生产批号 1 升序").get_by_role("textbox").fill("UI测试用")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_wave_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="波次策略").click()
        logged_in_page.locator(".action_btn > div > .ant-btn").first.click()
        expect(logged_in_page.get_by_label("波次策略分组")).to_have_value("波次");
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.locator(".action_btn > div:nth-child(2) > .ant-btn").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_loading_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="装车策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="查看").click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()

    def test_examine_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="审单策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="查看").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("gridcell", name="Press Space to toggle row").locator("div").nth(1).click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()

    def test_performance_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="绩效策略").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()

    def test_out_order_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="出库策略").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_box_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="箱标签策略").click()
        logged_in_page.get_by_role("button", name="停用").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="启用").first.click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="重置").click()
        logged_in_page.get_by_role("button", name="搜索").click()

    def test_shipping_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="发运单保价策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("货主").click()
        logged_in_page.get_by_title("智汇奇策科技有限公司").click()
        logged_in_page.get_by_label("策略编码").click()
        logged_in_page.get_by_label("策略编码").fill("testui")
        logged_in_page.get_by_label("策略名称").click()
        logged_in_page.get_by_label("策略名称").fill("UI测试用")
        logged_in_page.get_by_label("是否启用").click()
        logged_in_page.get_by_title("停用").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_label("策略明细名称").click()
        logged_in_page.get_by_label("策略明细名称").fill("UI测试用")
        logged_in_page.locator(".ant-select-selection-overflow").first.click()
        logged_in_page.get_by_title("零售事业部").click()
        logged_in_page.locator(
            "div:nth-child(3) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-overflow").click()
        logged_in_page.get_by_title("智汇奇策托运公司").click()
        logged_in_page.locator(
            "div:nth-child(4) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector > .ant-select-selection-overflow").click()
        logged_in_page.get_by_title("网店发货单").click()
        logged_in_page.locator(
            "div:nth-child(5) > .ant-row > div:nth-child(2) > .ant-form-item-control-input > .ant-form-item-control-input-content > .ant-select > .ant-select-selector").click()
        logged_in_page.get_by_title("ToB").click()
        logged_in_page.get_by_label("保价维度").click()
        logged_in_page.get_by_title("订单原销售额").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).fill("1")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).fill("1")
        logged_in_page.get_by_label("新增").locator("#form_item_isEnable").click()
        logged_in_page.get_by_label("新增").get_by_title("停用").click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("table").get_by_role("button", name="编辑").click()
        logged_in_page.get_by_label("编辑").get_by_role("button", name="取 消").click()
        logged_in_page.locator("span").filter(has_text="智汇奇策科技有限公司").click()
        logged_in_page.get_by_title("青岛啤酒有限公司").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.locator("#app").get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_container_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="容器调度策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("策略编码").click()
        logged_in_page.get_by_label("策略编码").fill("testui")
        logged_in_page.get_by_label("策略名称").click()
        logged_in_page.get_by_label("策略名称").fill("UI测试用")
        logged_in_page.get_by_label("库区").click()
        logged_in_page.get_by_title("虚拟拆零复核库区").click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("1")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).fill("1")
        logged_in_page.get_by_label("是否启用").click()
        logged_in_page.get_by_title("启用", exact=True).click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("ui测试用")
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-row-odd > div > .ag-cell-wrapper > .ag-selection-checkbox").click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-cell-focus > .ag-cell-wrapper").click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").nth(1).click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").nth(1).click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-row-odd > div > .ag-cell-wrapper > .ag-selection-checkbox").click()
        logged_in_page.get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_ship_fee_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="运费策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_label("策略名称").click()
        logged_in_page.get_by_label("策略名称").fill("UI测试用")
        logged_in_page.get_by_label("承运商").click()
        logged_in_page.get_by_title("智汇奇策托运公司").click()
        logged_in_page.get_by_label("省").click()
        logged_in_page.get_by_title("北京").click()
        logged_in_page.get_by_label("市").click()
        logged_in_page.get_by_title("北京市").click()
        logged_in_page.get_by_label("区县").click()
        logged_in_page.get_by_title("东城区").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.click()
        logged_in_page.get_by_role("spinbutton", name="请输入").first.fill("10")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(1).fill("10")
        logged_in_page.get_by_label("是否启用").click()
        logged_in_page.get_by_title("停用").click()
        logged_in_page.get_by_label("备注").click()
        logged_in_page.get_by_label("备注").fill("UI测试用")
        logged_in_page.get_by_role("button", name="新 增").nth(1).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(2).fill("10")
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(3).click()
        logged_in_page.get_by_role("spinbutton", name="请输入").nth(3).fill("10")
        logged_in_page.get_by_label("新增").locator("#form_item_isEnable").click()
        logged_in_page.get_by_label("新增").get_by_title("启用", exact=True).click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.locator("#app").get_by_role("button", name="删 除").click()
        logged_in_page.get_by_role("dialog").get_by_role("button", name="确 定").click()

    def test_auto_allocation_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="非自动分配策略").click()
        logged_in_page.get_by_role("button", name="新 增").click()
        logged_in_page.get_by_role("button", name="取 消").click()
        logged_in_page.get_by_role("button", name="查看").click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.get_by_role("button", name="编辑").click()
        logged_in_page.get_by_role("button", name="确 认").click()

    def test_tms_strategy_page(self, logged_in_page: Page) -> None:
        logged_in_page.locator("li").filter(has_text="首页").click()
        logged_in_page.reload()
        logged_in_page.locator("li").filter(has_text="策略中心").click()
        logged_in_page.locator("li").filter(has_text="同步TMS策略").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="停 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="查看").first.click()
        logged_in_page.get_by_role("button", name="关 闭").click()
        logged_in_page.get_by_role("button", name="编辑").first.click()
        logged_in_page.get_by_role("button", name="确 认").click()
        logged_in_page.locator(".ag-selection-checkbox").first.click()
        logged_in_page.get_by_role("button", name="启 用").click()
        logged_in_page.get_by_role("button", name="确 定").click()
        logged_in_page.get_by_role("button", name="搜索").click()
